// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	GetAllMessagesByStatus(ctx context.Context, status MessageSendingStatus) ([]GetAllMessagesByStatusRow, error)
	GetMessagesByStatusWithLimit(ctx context.Context, arg GetMessagesByStatusWithLimitParams) ([]GetMessagesByStatusWithLimitRow, error)
	UpdateMessageId(ctx context.Context, arg UpdateMessageIdParams) error
	UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error
}

var _ Querier = (*Queries)(nil)
